### PR TITLE
Create request button

### PR DESCRIPTION
**Pull request by tillprochaska**
Screenshot 2020-05-21 12 13 55

**UX:**
* Adds a primary action button to the requests listing.
* Changes UI copy containing "Recherche" or "Recherchefrage" to "Frage"

**Tech:**
The `PageTitle` component now has a `action` content area/slot:

```ruby
<%= c 'page_title' do |c| %>
  Fragen

  <% c.with(:actions) do %>
    <!-- primary action button -->
  <% end %>
<% end %>
```

### CODE REVIEW

**Comment by drjakob** [comment]
Statt Überschrift "FRAGEN" muss der TITEL DER RECHERCHE angezeigt werden (z.B. "Wohnen", "67survivors")
Zu dieser RECHERCHE kann man eine NEUE FRAGE STELLEN.

**Comment by drjakob** [comment]
FRAGEN sind Kinder von RECHERCHEN

**Comment by tillprochaska** [comment]
Ja – aber momentan haben wir noch keine Recherchen, nur Fragen.

**Comment by tillprochaska** [comment]
> One thing: Is it good UX to have a new button in the top right corner? I'm used to have this button as a sticky button in the bottom right corner (I believe that's according to the material spec). Another solution which I like is to place the button in a list where a new item would be inserted. Ie. in the list as a new item on top. Opinions?

Good question and I’m not 100% decided on this. I think it doesn’t come unexpected in the top-right, although I like the idea of having it as the first item of this list. That’d take way more space though, and thus you will have less space to display the actual list of requests…

**Comment by FrauCsu** [comment]
Top right corner is intuitive and the right spot for the button "create new request" "neue Frage stellen"

**Comment by roschaefer** [comment]
@tillprochaska please rebase and merge :heart:

**Pull request merged**
