### PR TITLE
Feat: scope message routes

### PR DESCRIPTION
**Pull request by soey**

### CODE REVIEW

**Review by roschaefer — CHANGES_REQUESTED** [review]
image

**Comment by soey** [comment]
really a nice catch @roschaefer .. fixed with https://github.com/tactilenews/100eyes/pull/1966/commits/1b4dd06804799001bcfaa5ac4b582028511ef2d0

**Review by roschaefer — CHANGES_REQUESTED** [review]
I'm on 8c8e258a2121bb24849818807292ec7dabcca729 and I still see these:

image

**Comment by soey** [comment]
> I'm on [8c8e258](https://github.com/tactilenews/100eyes/commit/8c8e258a2121bb24849818807292ec7dabcca729) and I still see these:
> 
> image

Maybe JS not reloaded? I can't reproduce it:

image

**Review by roschaefer — APPROVED** [review]
Yes, the culprint was a missing `npm run dev` and cached files locally

**Pull request merged**
