### PR TITLE
257 request metrics

### LINKED ISSUE #257: Show METRICS when looking at requests and replies
As editor
I want to have metrics that tell me
how many people have received a request from me
how many people have answered a request from me
how many have sent data (pictures or sound files)
how many have been starred as "useful"

### PR DESCRIPTION
**Pull request by tillprochaska**
Close #257. Merge #318 first.

**To Do:**

- [ ] Aggregate and show no. of highlighted messages
- [ ] Aggregate and show no. of contributors that received a request
- [x] Rename `RequestMiniStats` to `RequestMiniMetrics`
- [x] Use `Metric` component for `RequestMiniMetrics`
- [x] Move card styles from `Box` into separate `Card` component

In order to keep the scope of this PR smaller, I decided not to include changes necessary to aggregate additional stats (total no. users that received a request, no. of highlighted messages). I’ve created a new issue #322 for these two metrics.

***

Bildschirmfoto 2020-08-20 um 12 30 20

### CODE REVIEW

**Comment by FrauCsu** [comment]
Agreed

**Review by roschaefer — APPROVED** [review]
This looks good, too! Can we merge this early on? Maybe before we implement the two remaining checkboxes?

**Comment by tillprochaska** [comment]
That of what I wanted to do. I versteif a separate issue for the remaining tasks.

**Review by drjakob — APPROVED** [review]
Look great

**Pull request merged**
