### PR TITLE
Add basic custom errors pages

### LINKED ISSUE #1765: Custom error page
As editor I wish I get
an otter as a custom error page
in order ti have fun

### PR DESCRIPTION
**Pull request by mattwr18**
### What changed in this PR and why

This PR adds custom error pages to improve the overall UX when encountering bugs or pages that do not exist.
With the introduction of basic authorization to prevent users from visiting other organizations pages, we make use of more 404s so we find the need to improve the UI/UX.

Closes #1765

### CODE REVIEW

**Comment by mattwr18** [comment]
This is what the pages currently look like:

404:

Screenshot_20240828_120623

500:
Screenshot_20240828_120654

Note that I did remove the period from the heading as I didn't think it necessary.

**Comment by mattwr18** [comment]
This passes the build, but it makes the output noisier @soey ... there are a lot of these types of output:

```
Error during failsafe response: Missing template errors/internal_server_error, application/internal_server_error with {:locale=>[:de], :formats=>[:json], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby]}. Searched in:
  * "/home/runner/work/100eyes/100eyes/app/views"
  * "/home/runner/work/100eyes/100eyes/vendor/bundle/ruby/3.0.0/gems/administrate-field-jsonb-0.4.6/app/views"
  * "/home/runner/work/100eyes/100eyes/vendor/bundle/ruby/3.0.0/gems/administrate-field-active_storage-0.3.8/app/views"
  * "/home/runner/work/100eyes/100eyes/vendor/bundle/ruby/3.0.0/gems/administrate_exportable-0.6.1/app/views"
  * "/home/runner/work/100eyes/100eyes/vendor/bundle/ruby/3.0.0/gems/administrate-0.18.0/app/views"
  * "/home/runner/work/100eyes/100eyes/vendor/bundle/ruby/3.0.0/gems/kaminari-core-1.2.2/app/views"
  * "/home/runner/work/100eyes/100eyes/vendor/bundle/ruby/3.0.0/gems/clearance-2.6.1/app/views"
  * "/home/runner/work/100eyes/100eyes/vendor/bundle/ruby/3.0.0/gems/view_component-2.83.0/app/views"
  * "/home/runner/work/100eyes/100eyes/vendor/bundle/ruby/3.0.0/gems/actionmailbox-6.1.7.7/app/views"
 ```

**Comment by soey** [comment]
> This passes the build, but it makes the output noisier @soey ... there are a lot of these types of output:
> 
> ```
> Error during failsafe response: Missing template errors/internal_server_error, application/internal_server_error with {:locale=>[:de], :formats=>[:json], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby]}. Searched in:
>   * "/home/runner/work/100eyes/100eyes/app/views"
>   * "/home/runner/work/100eyes/100eyes/vendor/bundle/ruby/3.0.0/gems/administrate-field-jsonb-0.4.6/app/views"
>   * "/home/runner/work/100eyes/100eyes/vendor/bundle/ruby/3.0.0/gems/administrate-field-active_storage-0.3.8/app/views"
>   * "/home/runner/work/100eyes/100eyes/vendor/bundle/ruby/3.0.0/gems/administrate_exportable-0.6.1/app/views"
>   * "/home/runner/work/100eyes/100eyes/vendor/bundle/ruby/3.0.0/gems/administrate-0.18.0/app/views"
>   * "/home/runner/work/100eyes/100eyes/vendor/bundle/ruby/3.0.0/gems/kaminari-core-1.2.2/app/views"
>   * "/home/runner/work/100eyes/100eyes/vendor/bundle/ruby/3.0.0/gems/clearance-2.6.1/app/views"
>   * "/home/runner/work/100eyes/100eyes/vendor/bundle/ruby/3.0.0/gems/view_component-2.83.0/app/views"
>   * "/home/runner/work/100eyes/100eyes/vendor/bundle/ruby/3.0.0/gems/actionmailbox-6.1.7.7/app/views"
> ```
It's already too much noise .. can we get rid of this please?

**Comment by mattwr18** [comment]
I'm not sure how @soey

**Comment by mattwr18** [comment]
> It's already too much noise .. can we get rid of this please?

Ok, I figured it out. We need to also have a json response in the case we run into an error from one of our webhooks. See ca60a6b48a5955d5578dd69d5c8b1683487c20ff

**Review by soey — APPROVED** [review]

**Pull request merged**
