### PR TITLE
Miz logo

### PR DESCRIPTION
**Pull request by tillprochaska**
Screen Shot 2020-10-05 at 16 16 50

### CODE REVIEW

**Comment by drjakob** [comment]
Looks good to me

**Comment by FrauCsu** [comment]
reduce space line between logos if possible, @tillprochaska

**Comment by tillprochaska** [comment]
> reduce space line between logos if possible, @tillprochaska

@FrauCsu Done.

**Comment by FrauCsu** [comment]
Lo es prefecto!

**Review by FrauCsu — COMMENTED** [review]
Great job, well done!

**Review by FrauCsu — APPROVED** [review]

**Pull request merged**
