### PR TITLE
275 facelift

### LINKED ISSUE #246: Buttons should be PINK
Call to action buttons need to scream: ACTION
therefore they should be PINK

### LINKED ISSUE #252: "read less" Button
For overlong answers I need an analogous function to "read more", which is called "read less"

### LINKED ISSUE #275: Landingspage Facelift
Landingpage needs FACELIFT for better UX

- change Typo / Letters
- delete unnecessary boxes
- add logos
- add "how to" (4 steps)
- add footer

### PR DESCRIPTION
**Pull request by tillprochaska**
Close #275 
Close #246 
Close #252 

***
<details>
<summary>
Streamlined Requests Index (screenshots)
</summary>

Bildschirmfoto 2020-08-18 um 15 07 16
Bildschirmfoto 2020-08-18 um 15 05 22
</details>

<details>
<summary>
Streamlined Requests Page (screenshots)
</summary>

Bildschirmfoto 2020-08-18 um 15 23 56
</details>

<details>
<summary>
Expand and collapse long messages (#252) (screenshots)
</summary>

Bildschirmfoto 2020-08-18 um 15 33 14
Bildschirmfoto 2020-08-18 um 15 51 37
</details>

### CODE REVIEW

**Comment by drjakob** [comment]
Approved. What happened to the logo?

**Comment by FrauCsu** [comment]
Yes, Logo is missing

**Comment by tillprochaska** [comment]
> What happened to the logo?

> Yes, Logo is missing

There’s a separate issue for that (#245)

**Review by roschaefer — CHANGES_REQUESTED** [review]
facelift

This looks great and I tested this by looking at the browser.

Here's what I found:

Screenshot - 2020-08-20T193146 499

**Comment by tillprochaska** [comment]
> Here's what I found:

The border is actually intended as a focus indicator.

**Comment by roschaefer** [comment]
> > Here's what I found:
> 
> The border is actually intended as a focus indicator.

Fair enough, I'll approve

**Review by roschaefer — APPROVED** [review]

**Comment by drjakob** [comment]
Uff

**Pull request merged**
